Rebuilt OMAudioLib.dll
Old version was causing an error when starting OM:
Error: Unable to load foreign library (OMAUDIOLIB).
Could not register handle for external module :OMAUDIOLIB (file-name C:\Program Files\LispWorks\OMAudioLib.dll):
 %1 is not a valid Win32 application..