Replaced libsndfile-1.dll
Old version caused error upon opening OM:
Error: Unable to load any of the alternatives:
("C:\\Program Files\\LispWorks\\libsndfile-1.dll" (:DEFAULT "libsndfile-1"))